{% set version = "2.1.1" %}

package:
  name: ocgis
  version: {{ version }}

source:
  url: https://github.com/NCPP/ocgis/archive/v{{ version }}.tar.gz
  sha256: f071685ab201d879e0efb0a7d7107e24b11c40e3bf8c7907502e8f68ff646657

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cf-units
    - fiona
    - mpi4py
    - mpich
    - netcdf4 <1.4
    - numpy
    - pyproj
    - rtree
    - shapely
    - six

test:
  requires:
    - nose
    - mock
  imports:
    - ocgis
  commands:
    - ocli chunked-rwg --help

about:
  home: http://ocgis.readthedocs.io/en/latest/
  license: NCSA
  license_file: LICENSE.txt
  summary: 'OpenClimateGIS (OCGIS) provides geoprocessing and calculation tools for spatiotemporal datasets.'

extra:
  recipe-maintainers:
    - bekozi
    - ocefpaf
