#{% set version = "2.0.0.dev1" %}

package:
  name: ocgis
  version: 2.0.0.dev1
#  version: {{ version }}

source:
  git_tag: v-2.0.0.dev1
  git_url: https://github.com/NCPP/ocgis.git
#  fn: ocgis-{{ version }}.tar.gz
#  url: https://github.com/NCPP/ocgis/archive/v{{ version }}.tar.gz
#  sha256: d76ca32d81bdf52a71dde48a7641085ff280b9d9fea0a294fda3308942ca5230

build:
  number: 0
#  skip: True  # [py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cf_units
    - fiona
    - netcdf4
    - numpy
    - shapely
    - rtree
    - pyproj
    - mpi4py

test:
  requires:
    - nose
  imports:
    - ocgis

about:
  home: http://ocgis.readthedocs.io/en/latest/
  license: NCSA
  summary: 'OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.'

extra:
  recipe-maintainers:
    - bekozi
    - ocefpaf
