travis:
  secure:
    BINSTAR_TOKEN: AtjXcIcNlY3kFhcU5ycExwiCPn8YI0xf0wur1g3RccZIHrEBB98J82ropp9XjL/A3h+IAhtXSg935IKwaFed1rIvnYnSRWuUMSYXDWIFbptjeC4uNMceZLRSa2qQOuSVEaKtIdD6ynXH0ubW2gC7H8LigeITh/ge8DPBNXw0ogmH8USrAtu//7uB2COofNx+xxCChqSxrfk57BbErOqteiX8CpUQwd1UmM/g0HISb/jXRiwyHexRpr9T2narIrWf0z20305amWXEofFG/UDQN+uduMEgEQzSQ3gdIurPKk8tNm/+3knsJMrlULGdUYHKLxgkvHo/HkSBgyIb+8Rz4pQ/mE27sv88pwasajpBovtOJDNYlpD4np2JDgtUt8W+89NXAClaJdnal680rSlKGbJnQxtD5EUs/ELNlH8OEh7WNr2Xc8m3mRrBv9KPNK2JCeoOLavxP7K3hul02le28uf6gFbR7QzhDaaoNsZE8EZSFxSEY9xR27B2f2A6LkY9C7pudSm1gNz8kuIN9ZFiD8uD5U0lifOdeXgH4sV5m+PFk5hrQ3YwgN2KZWNqz19AzZZ9Bv4qX+Mfw9dWKuPaw6DWd1j5FD4yWYJGSfliDsd+pdHhj44O8RYz2IZQ0LxDW6SycCdSpuIDFnYzDNFriCCvD/Lkbthh1HTmaWgZZGE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
